# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('documentId', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=3)),
                ('photo', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('map', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberRooms', models.IntegerField()),
                ('livesWith', models.IntegerField()),
                ('runningWater', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('petsExtra', models.CharField(max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mia.Patient')),
            ],
        ),
    ]
